routes/web.php
<?php
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// bật, tắt đăng kí và đổi mật khẩu
Auth::routes(['register' => true, 'reset' => true]);

// change password
Route::get('change-password', 'ChangePasswordController@index');

Route::post('change-password', 'ChangePasswordController@store')->name('change.password');

//giỏ hàng
Route::group(['prefix' => 'cart', 'as' => 'cart.'], function(){
    Route::post('add', 'CartController@add')->name('add');
    Route::get('list', 'CartController@list')->name('list');
    Route::get('delete/{id}', 'CartController@delete')->name('delete');
    Route::post('send', 'CartController@send')->name('send');
});

//login google
Route::get('/redirect', 'Auth\LoginController@redirectToProvider')->name("login.provider");
Route::get('/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/auth/redirect/{provider}', 'Auth\LoginController@redirect');
Route::get('/callback/{provider}', 'Auth\LoginController@callback');
//
Route::get('buy/domain', 'RegisHostingController@buyDomainForm')->name('buy-domain-form');
Route::post('buy/domain', 'RegisHostingController@buyDomain')->name('buy-domain');

// Liên hệ
Route::get('/contact', [
    'uses' => 'ContactUsFormController@createForm'
])->name('contact');

Route::post('/contact', [
    'uses' => 'ContactUsFormController@ContactUsForm',
    'as' => 'contact.store'
]);

//facebook face
Route::get('/facebook', [
    'uses' => 'FacebookFormController@createForm'
])->name('facebook');

Route::post('/facebook', [
    'uses' => 'FacebookFormController@FacebookForm',
    'as' => 'facebook.store'
]);

Route::get('/facebookdanhsach/', 'FacebookFormController@getDanhSach');
Route::get('/contactdanhsach/', 'ContactUsFormController@getDanhSach');

// Sản phẩm Domain
Route::get('/sanpham/sanphamdomain', 'SPDomainController@getHome')->name('sanphamdomain');
Route::get('/sanpham/sanphamdomain', 'SPDomainController@index')->name('sanphamdomain');

// Sản phẩm Hosting
Route::get('/sanpham/sanphamhosting', 'SPHostingController@getHome')->name('sanphamhosting');
Route::get('/sanpham/sanphamhosting', 'SPHostingController@index')->name('sanphamhosting');

// Đăng ký hosting
Route::get('/sanpham/regishosting', 'RegisHostingController@getHome')->name('regishosting');
Route::get('/sanpham/regishosting', 'RegisHostingController@index')->name('regishosting');

Route::get('/sanpham/giohang/', 'RegisHostingController@getDanhSach')->name('cart');
Route::get('/sanpham/duyetdon/{id}', 'RegisHostingController@accept')->name('accept-cart');

Route::get('/sanpham/regishosting', 'RegisHostingController@getThem');
Route::post('/sanpham/regishosting', 'CartController@postThem');

Route::get('/sanpham/giohang{id}', 'RegisHostingController@getSua');
Route::post('/sanpham/giohang{id}', 'RegisHostingController@postSua');

Route::get('/sanpham/giohang{id}', 'RegisHostingController@getXoa')->name('delete-donhang');
Route::post('/sanpham/giohang{id}', 'RegisHostingController@postXoa');

// welcome
Route::get('/', function () {
	return view('welcome');
});

Route::get('ma-giam-gia/them', 'DiscountCodeController@discountCodeAddForm')->name('discount-code-add-form');
Route::post('ma-giam-gia/them', 'DiscountCodeController@discountCodeAdd')->name('discount-code-add');

Route::get('doanhthu', 'RegisHostingController@revenue')->name('doanhthu');

// Home
Route::get('/home', 'HomeController@getHome')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

// Domain
Route::get('/domain', 'DomainController@getDanhSach');

Route::get('/domain/them', 'DomainController@getThem');
Route::post('/domain/them', 'DomainController@postThem');

Route::get('/domain/sua/{id}', 'DomainController@getSua');
Route::post('/domain/sua/{id}', 'DomainController@postSua');

Route::get('/domain/xoa/{id}', 'DomainController@getXoa');
Route::post('/domain/xoa/{id}', 'DomainController@postXoa');

Route::post('/domain/nhap', 'DomainController@postNhap');
Route::get('/domain/xuat', 'DomainController@getXuat');

// Khách hàng
Route::get('/khachhang', 'KhachHangController@getDanhSach');

Route::get('/khachhang/them', 'KhachHangController@getThem');
Route::post('/khachhang/them', 'KhachHangController@postThem');

Route::get('/khachhang/sua/{id}', 'KhachHangController@getSua');
Route::post('/khachhang/sua/{id}', 'KhachHangController@postSua');

Route::get('/khachhang/xoa/{id}', 'KhachHangController@getXoa');
Route::post('/khachhang/xoa/{id}', 'KhachHangController@postXoa');

Route::post('/khachhang/nhap', 'KhachHangController@postNhap');
Route::get('/khachhang/xuat', 'KhachHangController@getXuat');

//Hosting
Route::get('/hosting', 'HostingController@getDanhSach');

Route::get('/hosting/them', 'HostingController@getThem');
Route::post('/hosting/them', 'HostingController@postThem');

Route::get('/hosting/sua/{id}', 'HostingController@getSua');
Route::post('/hosting/sua/{id}', 'HostingController@postSua');

Route::get('/hosting/xoa/{id}', 'HostingController@getXoa');
Route::post('/hosting/xoa/{id}', 'HostingController@postXoa');

//Bai viet
Route::get('/baiviet', 'BaiVietController@getDanhSach')->name("baiviet");

Route::get('/baiviet/them', 'BaiVietController@getThem');
Route::post('/baiviet/them', 'BaiVietController@postThem');

Route::get('/baiviet/sua/{id}', 'BaiVietController@getSua');
Route::post('/baiviet/sua/{id}', 'BaiVietController@postSua');

Route::get('/baiviet/xoa/{id}', 'BaiVietController@getXoa');
Route::post('/baiviet/xoa/{id}', 'BaiVietController@postXoa');

//Nguoi Dung (tai khoan)
Route::get('/nguoidung', 'DSNguoiDungController@getDanhSach')->name("nguoidung");

Route::get('/nguoidung/them', 'DSNguoiDungController@getThemHinhAnh');
Route::post('/nguoidung/them', 'DSNguoiDungController@postThemHinhAnh');

Route::get('/nguoidung/sua/{id}', 'DSNguoiDungController@getSua');
Route::post('/nguoidung/sua/{id}', 'DSNguoiDungController@postSua');

Route::get('/nguoidung/xoa/{id}', 'DSNguoiDungController@getXoa');
Route::post('/nguoidung/xoa/{id}', 'DSNguoiDungController@postXoa');

app/Cart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
    protected $table = 'carts';

    protected $fillable = ['nguoidung_id', 'product', 'type', 'price', 'time'];
}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Cart;
use App\Domain;
use App\RegisHosting;
use App\Order;
use DB;

class CartController extends Controller
{

    public function list()
    {
        $discountCodes = DB::table('discount_codes')->where('expire', '>=', date('Y-m-d'))->get();
        $userId = auth()->user()->id;
        $carts = Cart::where('nguoidung_id', $userId)->latest()->get();
        $total = Cart::where('nguoidung_id', $userId)->sum('price');

        return view('carts.list', compact('carts', 'total', 'discountCodes'));
    }

    public function send(Request $request)
    {
        $userId = auth()->user()->id;
        $carts = Cart::where('nguoidung_id', $userId)->latest()->get();
        $order = Order::create([
            'nguoidung_id' => auth()->user()->id,
            'discount' => $request->code,
            'diachi' => $request->diachi,
            'sdt' => $request->sdt
        ]);
        foreach($carts as $item) {
            RegisHosting::create([
                'nguoidung_id' => $item->nguoidung_id,
                'loaihosting' => $item->product,
                'type' => $item->type,
                'price' => $item->price,
                'time' => $item->time,
                'order_id' => $order->id
            ]);
        }
        Cart::where('nguoidung_id', $userId)->delete();

        return back()->with('success', 'Gửi đơn hàng thành công, vui lòng đợi chúng tôi xác nhận');
    }

    public function add(Request $request)
    {
        $check = Domain::where('tendomain', $request->product)->first();

        if (empty($check)) {
            Cart::updateOrCreate(
                [
                    'product' => $request->product,
                    'nguoidung_id' => auth()->user()->id
                ],
                [
                    'price' => $request->price,
                    'type' => $request->type,
                    'time' => $request->time,
                ]
            );

            return 1;
        } else {
            return 0;
        }
    }

    public function delete($id)
    {
        Cart::where('id', $id)->delete();

        return back()->with('success', 'Xóa thành công');
    }

    // Mua hosting
	public function postThem(Request $request)
	{
		if (!auth()->check()) {
			return redirect('/register');
		}	
        $inputs = $request->all();
        $price = $inputs['option'] * 1000 * $inputs['time'];

        Cart::create(
            [
                'product' => $inputs['product'],
                'nguoidung_id' => auth()->user()->id,
                'price' => $price,
                'type' => 1,
                'time' => $inputs['time'],
            ]
        );

		return back()->with('success', 'ok');
	}
}

resources/views/carts/list.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="card">
		<div class="card-header">Giỏ hàng</div>
		<div class="card-body">
			<div class="row">
                <div class="col-lg-12">
                <form action="{{route('cart.send')}}" method="post">
                        @csrf
                    <table style="width: 100%">
                        <tr>
                            <th>Sản phẩm</th>
                            <th>Thời gian</th>
                            <th>Giá</th>
                            <th>
                                Thao tác
                            </th>
                        </tr>
                        @foreach($carts as $item)
                            <tr>
                                <td>
                                    {{$item->product}}
                                </td>
                                <td>
                                    {{$item->time}} tháng
                                </td>
                                <td style="text-align: right">
                                    {{number_format($item->price)}}
                                </td>
                                <td>
                                    <a class="btn btn-danger" href="{{route('cart.delete', ['id' => $item->id])}}">
                                        Xóa
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        <tr>
                            <td colspan="2" style="text-align: right">
                                Tổng: 
                            </td>
                            <td style="text-align: right">
                                {{number_format($total)}}
                            </td>
                            <td></td>
                        </tr>
                        <tr>
                            <td style="text-align: right" colspan="2">Mã giảm giá (nếu có)</td>
                            <td>
                                @foreach($discountCodes as $code)
                                    <label for="">
                                        <input name="code" onclick="pick({{$code->discount}})" type="radio" value="{{$code->discount}}">
                                        {{$code->name}}
                                    </label>
                                    <br>
                                @endforeach
                            </td>
                            <td></td>
                        </tr>
                        <tr>
                            <td style="text-align: right" colspan="2">Thành tiền</td>
                            <td style="text-align: right">
                                <span id="last-price">{{number_format($total)}}</span>
                                
                            </td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>
                                <label>Địa chỉ</label>
                            </td>
                            <td colspan="3">
                                <div class="form-group">
                                    <input type="text" required class="form-control @error('diachi') is-invalid @enderror" id="diachi" name="diachi"/>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label>Số điện thoại</label>
                            </td>
                            <td colspan="3">
                                <div class="form-group">
                                    <input type="text" required class="form-control @error('sdt') is-invalid @enderror" id="sdt" name="sdt"/>
                                </div>
                            </td>
                        </tr>
                    </table>
                    <br><br>
                    <center>
                        <button type="submit" class="btn btn-primary">Gửi đơn hàng</button>
                    </center>
                </form>
                    
                </div>
                <div class="col-lg-4">
                    
                </div>
            </div>
		</div>
	</div>
</div>
<style>
    table tr td, table tr th{
        padding: 20px;
        border: 1px solid #ccc;
    }
</style>
<script>
    function pick(discount)
    {
        total = "{{$total}}";
        lastPrice =  total - total * discount/100;
        $('#last-price').html(lastPrice);
        //alert(discount);

    }
	@if(session('success'))
		Swal.fire({
			title: "{{session('success')}}",
			icon: "success",
			confirmButtonText: 'OK'
		});
	@endif
</script>
@endsection