routes/web.php
<?php
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// bật, tắt đăng kí và đổi mật khẩu
Auth::routes(['register' => true, 'reset' => true]);

// change password
Route::get('change-password', 'ChangePasswordController@index');

Route::post('change-password', 'ChangePasswordController@store')->name('change.password');

//giỏ hàng
Route::group(['prefix' => 'cart', 'as' => 'cart.'], function(){
    Route::post('add', 'CartController@add')->name('add');
    Route::get('list', 'CartController@list')->name('list');
    Route::get('delete/{id}', 'CartController@delete')->name('delete');
    Route::post('send', 'CartController@send')->name('send');
});

//login google
Route::get('/redirect', 'Auth\LoginController@redirectToProvider')->name("login.provider");
Route::get('/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/auth/redirect/{provider}', 'Auth\LoginController@redirect');
Route::get('/callback/{provider}', 'Auth\LoginController@callback');
//
Route::get('buy/domain', 'RegisHostingController@buyDomainForm')->name('buy-domain-form');
Route::post('buy/domain', 'RegisHostingController@buyDomain')->name('buy-domain');

// Liên hệ
Route::get('/contact', [
    'uses' => 'ContactUsFormController@createForm'
])->name('contact');

Route::post('/contact', [
    'uses' => 'ContactUsFormController@ContactUsForm',
    'as' => 'contact.store'
]);

//facebook face
Route::get('/facebook', [
    'uses' => 'FacebookFormController@createForm'
])->name('facebook');

Route::post('/facebook', [
    'uses' => 'FacebookFormController@FacebookForm',
    'as' => 'facebook.store'
]);

Route::get('/facebookdanhsach/', 'FacebookFormController@getDanhSach');
Route::get('/contactdanhsach/', 'ContactUsFormController@getDanhSach');

// Sản phẩm Domain
Route::get('/sanpham/sanphamdomain', 'SPDomainController@getHome')->name('sanphamdomain');
Route::get('/sanpham/sanphamdomain', 'SPDomainController@index')->name('sanphamdomain');

// Sản phẩm Hosting
Route::get('/sanpham/sanphamhosting', 'SPHostingController@getHome')->name('sanphamhosting');
Route::get('/sanpham/sanphamhosting', 'SPHostingController@index')->name('sanphamhosting');

// Đăng ký hosting
Route::get('/sanpham/regishosting', 'RegisHostingController@getHome')->name('regishosting');
Route::get('/sanpham/regishosting', 'RegisHostingController@index')->name('regishosting');

Route::get('/sanpham/giohang/', 'RegisHostingController@getDanhSach')->name('cart');
Route::get('/sanpham/duyetdon/{id}', 'RegisHostingController@accept')->name('accept-cart');

Route::get('/sanpham/regishosting', 'RegisHostingController@getThem');
Route::post('/sanpham/regishosting', 'CartController@postThem');

Route::get('/sanpham/giohang{id}', 'RegisHostingController@getSua');
Route::post('/sanpham/giohang{id}', 'RegisHostingController@postSua');

Route::get('/sanpham/giohang{id}', 'RegisHostingController@getXoa')->name('delete-donhang');
Route::post('/sanpham/giohang{id}', 'RegisHostingController@postXoa');

// welcome
Route::get('/', function () {
	return view('welcome');
});

Route::get('ma-giam-gia/them', 'DiscountCodeController@discountCodeAddForm')->name('discount-code-add-form');
Route::post('ma-giam-gia/them', 'DiscountCodeController@discountCodeAdd')->name('discount-code-add');

Route::get('doanhthu', 'RegisHostingController@revenue')->name('doanhthu');

// Home
Route::get('/home', 'HomeController@getHome')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

// Domain
Route::get('/domain', 'DomainController@getDanhSach');

Route::get('/domain/them', 'DomainController@getThem');
Route::post('/domain/them', 'DomainController@postThem');

Route::get('/domain/sua/{id}', 'DomainController@getSua');
Route::post('/domain/sua/{id}', 'DomainController@postSua');

Route::get('/domain/xoa/{id}', 'DomainController@getXoa');
Route::post('/domain/xoa/{id}', 'DomainController@postXoa');

Route::post('/domain/nhap', 'DomainController@postNhap');
Route::get('/domain/xuat', 'DomainController@getXuat');

// Khách hàng
Route::get('/khachhang', 'KhachHangController@getDanhSach');

Route::get('/khachhang/them', 'KhachHangController@getThem');
Route::post('/khachhang/them', 'KhachHangController@postThem');

Route::get('/khachhang/sua/{id}', 'KhachHangController@getSua');
Route::post('/khachhang/sua/{id}', 'KhachHangController@postSua');

Route::get('/khachhang/xoa/{id}', 'KhachHangController@getXoa');
Route::post('/khachhang/xoa/{id}', 'KhachHangController@postXoa');

Route::post('/khachhang/nhap', 'KhachHangController@postNhap');
Route::get('/khachhang/xuat', 'KhachHangController@getXuat');

//Hosting
Route::get('/hosting', 'HostingController@getDanhSach');

Route::get('/hosting/them', 'HostingController@getThem');
Route::post('/hosting/them', 'HostingController@postThem');

Route::get('/hosting/sua/{id}', 'HostingController@getSua');
Route::post('/hosting/sua/{id}', 'HostingController@postSua');

Route::get('/hosting/xoa/{id}', 'HostingController@getXoa');
Route::post('/hosting/xoa/{id}', 'HostingController@postXoa');

//Bai viet
Route::get('/baiviet', 'BaiVietController@getDanhSach')->name("baiviet");

Route::get('/baiviet/them', 'BaiVietController@getThem');
Route::post('/baiviet/them', 'BaiVietController@postThem');

Route::get('/baiviet/sua/{id}', 'BaiVietController@getSua');
Route::post('/baiviet/sua/{id}', 'BaiVietController@postSua');

Route::get('/baiviet/xoa/{id}', 'BaiVietController@getXoa');
Route::post('/baiviet/xoa/{id}', 'BaiVietController@postXoa');

//Nguoi Dung (tai khoan)
Route::get('/nguoidung', 'DSNguoiDungController@getDanhSach')->name("nguoidung");

Route::get('/nguoidung/them', 'DSNguoiDungController@getThemHinhAnh');
Route::post('/nguoidung/them', 'DSNguoiDungController@postThemHinhAnh');

Route::get('/nguoidung/sua/{id}', 'DSNguoiDungController@getSua');
Route::post('/nguoidung/sua/{id}', 'DSNguoiDungController@postSua');

Route::get('/nguoidung/xoa/{id}', 'DSNguoiDungController@getXoa');
Route::post('/nguoidung/xoa/{id}', 'DSNguoiDungController@postXoa');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
	@include('layouts.header')
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="50">
	<div class="container-fluid">
		@include('layouts.container')
		
		<main class="pt-2">
				@yield('content')
		</main>
		
		@include('layouts.footer')
	
	</div>
</body>
</html>

resources/views/layouts/container.blade.php
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
	<a class="navbar-brand" href="{{ url('/') }}">
		<img src="{{ asset('public/images/logo.png') }}" width="30" height="30" class="d-inline-block align-top" alt="" />
		{{ config('app.name', 'Laravel') }}
	</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			@auth()
			@if(auth()->user()->level==1)
				<li class="nav-item"><a class="nav-link" href="{{ url('/domain') }}"><i class="fal fa-globe"></i> Tên miền</a></li>
				<li class="nav-item"><a class="nav-link" href="{{ url('/hosting') }}"><i class="fal fa-cloud"></i> Hosting</a></li>
				<li class="nav-item"><a class="nav-link" href="{{ url('/khachhang') }}"><i class="fal fa-users"></i> Khách Hàng</a></li>
				<li class="nav-item"><a class="nav-link" href="{{ url('/baiviet') }}"><i class="fal fa-edit"></i> Bài Viết</a></li>
				<li class="nav-item"><a class="nav-link" href="{{ url('/sanpham/giohang') }}"><i class="fal fa-shopping-bag"></i> Đơn hàng</a></li>
				<li class="nav-item"><a class="nav-link" href="{{ url('/contactdanhsach') }}"><i class="fal fa-envelope"></i> Danh sách liên hệ</a></li>
				<li class="nav-item"><a class="nav-link" href="{{ route('doanhthu') }}"><i class="fas fa-chart-line"></i> Doanh thu</a></li>
				<li class="nav-item"><a class="nav-link" href="{{ route('discount-code-add-form') }}"><i class="fas fa-sort-amount-down"></i> Mã giảm gía</a></li>
			@endif
			@endauth
		</ul>
		<ul class="navbar-nav ml-auto">

			@guest
			{{--
				<li class="nav-item"><a class="nav-link" href="{{ route('login') }}"><i class="fal fa-sign-in-alt"></i> Đăng nhập</a></li>
				<a href="{{ route('login.provider', 'google') }}" class="btn btn-secondary">{{ __('Google Sign in') }}</a>
				@if (Route::has('register'))
					<li class="nav-item"><a class="nav-link" href="{{ route('register') }}"><i class="fal fa-user-plus"></i> Đăng ký</a></li>
				@endif
			--}}
			@else
				<li class="nav-item">
					<img src="{{ asset('/public/images/icon/cart.svg') }}" width="60" height="30" alt="cart" />
					<a id="cart-text" class="nav-link" href="{{route('cart.list')}}">Giỏ hàng</a>
				</li>
				<li class="nav-item dropdown">
					<a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre><img class="rounded-circle" src="{{Auth::user()->avatar}}" width="40px;"/> {{ Auth::user()->name }} <span class="caret"></span></a>
					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{{ route('nguoidung') }}"><i class="fal fa-sign-out"></i>Thông tin tài khoản</a>
						<a class="dropdown-item" href="{{ route('change.password') }}"><i class="fal fa-sign-out"></i>Đổi mật khẩu</a>
						<a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fal fa-sign-out"></i> Đăng xuất</a>
						<form id="logout-form" action="{{ route('logout') }}" method="post" style="display: none;">@csrf</form>
					</div>
				</li>
			@endguest
		</ul>
	</div>
</nav>

resources/views/layouts/css.blade.php
<style>
	nav{
		background-color: #575B5B;
	}

	main{
		min-height:560px;
	}

	.all-center{
		display: flex;
	  	align-items: center;
	  	justify-content: center;
	}

	tr:hover {
		background-color:#f5f5f5;
	}

	footer {
	    bottom: 0;
	    width: 100%;
	}
	.footer-row1{
		padding-top: 2%;
		display: flex;
	  	align-items: center;
	  	justify-content: center;
	}
	.footer-row2{
		background: white;
		font-weight: bold;
	}
	.text-footer{
		color: white;
	}
	a.text-footer{
		color: white;
	}
	.logo-footer{
		padding: 4px;
	}

	#cart-text{
		color: #00b59c;
	}
</style>

resources/views/layouts/footer.blade.php
<!-- Page Footer-->
<footer class="page-footer font-small blue pt-4">
    <div class="container-fluid text-center text-md-left footer-row1 bg-dark">
      <div class="container">
        <div class="row">
            <div class="col-6 col-md-4">
                <h4 class="text-footer">ABOUT US</h4>
                <form class="">
                    <div class="list-us">
                        <img class="logo-footer" src="{{ asset('public/images/icon/adress.svg') }}" width="10%" height="10%" />
                        <a class="text-footer" href="#">Long Xuyên, An Giang</a>
                    </div>
                    <div class="list-us">
                        <img class="logo-footer" src="{{ asset('public/images/icon/phone.svg') }}" width="10%" height="10%" />
                        <a class="text-footer" href="tel:0332691871">Hotline: 0332691871</a>
                    </div>
                    <div class="list-us">
                        <img class="logo-footer" src="{{ asset('public/images/icon/email.svg') }}" width="10%" height="10%" />
                        <a class="text-footer" href="mailto:trongnghia.cl.tb.ag@gmail.com">Email: leo.angel.tb@gmail.com</a>
                    </div>
                    <div class="list-us">
                        <img class="logo-footer" src="{{ asset('public/images/icon/form.svg') }}" width="10%" height="10%" />
                        <a class="text-footer" href="{{route('contact')}}">Form liên hệ</a>
                    </div>
                </form>
              </div>
              <div class="col-6 col-md-4">
                <h4 class="text-footer">Chính sách</h4>
                <ul>
                    <a href="#"><p class="text-footer">Chính sách bảo mật</p></a>
                    <a href="#"><p class="text-footer">Chính sách đổi trả</p></a>
                    <a href="#"><p class="text-footer">Chính sách đại lý</p></a>
                </ul>
              </div>
              <div class="col-6 col-md-4">
                <a href="text-center">
                    <img class="logo-footer" src="{{ asset('public/images/logo.png') }}" width="20%" height="30%" /><a href="" class="h1">{{ config('app.name')}}</a>
                </a>
                
                <p class="text-footer">Công ty TNHH Công Nghệ NCP được thành lập từ tháng 10/2019 bởi các thành viên xuất thân từ các công ty hàng đầu về ISP, Datacenter, máy chủ và thiết bị tin học, mạng máy tính, truyền thông, và dịch vụ CNTT</p>
                <hr/>
                <div>
                    <ul>
                        <a class="text-footer">Theo dõi chúng tôi:</a>
                        <a href="https://www.facebook.com/htnghia.dh18pm/">
                            <img class="logo-footer" src="{{ asset('public/images/icon/facebook.svg') }}" width="10%" height="10%" />
                        </a>
                        <a>
                            <img class="logo-footer" src="{{ asset('public/images/icon/youtube.svg') }}" width="10%" height="10%" />
                        </a>
                        <a>
                            <img class="logo-footer" src="{{ asset('public/images/icon/twitter.svg') }}" width="10%" height="10%" />
                        </a>
                        <a>
                            <img class="logo-footer" src="{{ asset('public/images/icon/ins.svg') }}" width="10%" height="10%" />
                        </a>
                    </ul>
                </div>
            </div>
        </div>
      </div>
    </div>

    <div class="footer-row2">
      <div class="container">
        <div class="row row-10 align-items-center justify-content-sm-between">
          <div class="col-md-auto">
            <a class="rights"><span>Copy right {{ date('Y') }} &copy;&nbsp;</span><span class="copyright-year"></span><span>&nbsp;</span><span>{{ config('app.name', 'Laravel') }}</span><span>.&nbsp; All rights reserved</span></a>
          </div>
          <div class="col-md-auto order-md-1">Hosted by <a target="_blank"
            href="https://giayphut.com">Giayphut.com</a></div>
          <div class="col-md-auto">
                Power by <a href="">{{ config('app.name') }}</a>
          </div>
        </div>
      </div>
    </div>
</footer>

resources/views/layouts/header.blade.php
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
	
<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}" />
<base href="{{asset('')}}">
<title>{{ config('app.name', 'Laravel') }}</title>

<!-- Scripts -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
{{-- <script src="{{ asset('public/js/jquery-3.5.1.slim.min.js') }}" defer></script> --}}
<script src="{{ asset('public/js/popper.min.js') }}" defer></script>
<script src="{{ asset('public/js/bootstrap.min.js') }}" defer></script>
@yield('javascript')

<!-- Fonts -->
<link rel="dns-prefetch" href="//fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" />

<!-- Favicon -->
<link href="{{ asset('public/images/logo.png') }}" rel="shortcut icon" type="image/x-icon" />

<!-- Styles -->
<link href="{{ asset('public/css/bootstrap.min.css') }}" rel="stylesheet" />
<link href="{{ asset('public/css/fontawesome.min.css') }}" rel="stylesheet" />
<link href="{{ asset('public/css/custom.css') }}" rel="stylesheet" />
<script src="{{ asset('public/ckeditor_full/ckeditor.js') }}"></script>
<script>
	CKEDITOR.replace('noidung', {height: 1000});
</script>
<script src="{{ asset('public/js/alert.js') }}"></script>

@include('layouts.css')